# Generated by Django 5.2.8 on 2025-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_name",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_phone",
            field=models.CharField(default="N/A", max_length=15),
        ),
    ]
