# Generated by Django 5.2.8 on 2025-11-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0003_order_delivery_address_order_delivery_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
    ]
