# Generated by Django 5.2.8 on 2025-11-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0004_book_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("Cash", "Cash on Delivery"), ("Card", "Credit/Debit Card")],
                max_length=50,
            ),
        ),
    ]
