# Generated by Django 5.2.8 on 2025-11-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0005_alter_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
