# Generated by Django 5.2.8 on 2025-11-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0007_coupon_customer_is_first_time_buyer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("order", "Order Inquiry"),
                            ("book", "Book Recommendation"),
                            ("delivery", "Delivery Issue"),
                            ("feedback", "Feedback"),
                            ("partnership", "Partnership"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("resolved", "Resolved"),
                        ],
                        default="unread",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
