# Generated by Django 5.2.8 on 2025-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0008_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
